networks:
  traefik-network:
    external: true
  app-network:
    driver: bridge

services:
  confirmd_frontend:
    image: confirmd-wallet-demo-web
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    volumes:
      - type: bind
        source: ./client/Caddyfile
        target: /etc/caddy/Caddyfile
    ports:
      - '3000:3000'
    depends_on:
      - confirmd_backend
    environment:
      - REACT_APP_HOST_BACKEND=""
      - REACT_APP_BASE_ROUTE=""
      - REACT_APP_GA_MEASUREMENT_ID=G-XZSVD9FZMQ
    labels:
      #Traefik
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-network'
      #Routers
      - 'traefik.http.routers.confirmd_frontend.rule=Host(`getconfirmd.com`)'
      - 'traefik.http.routers.confirmd_frontend.entrypoints=websecure'
      - 'traefik.http.routers.confirmd_frontend.service=confirmd_frontend'

      - 'traefik.http.routers.confirmd_frontend.tls=true'
      - 'traefik.http.routers.confirmd_frontend.tls.certresolver=letsencrypt'
      - 'traefik.docker.network=traefik-network'

      - 'traefik.http.services.confirmd_frontend.loadbalancer.passhostheader=true'
      - 'traefik.http.routers.confirmd_frontend.middlewares=compresstraefik'
      - 'traefik.http.middlewares.compresstraefik.compress=true'

      # Services
      - 'traefik.http.services.confirmd_frontend.loadbalancer.server.port=3000'

    networks:
      - traefik-network
      - app-network

  confirmd_backend:
    image: bc-wallet-demo-server
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - '5555:5511'
    env_file:
      - ./server/.env
    networks:
      - traefik-network
      - app-network
    labels:
      #Traefik
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-network'
      #Routers
      - 'traefik.http.routers.confirmd_backend.rule=Host(`api.getconfirmd.com`)'
      - 'traefik.http.routers.confirmd_backend.entrypoints=websecure'
      - 'traefik.http.routers.confirmd_backend.service=confirmd_backend'

      - 'traefik.http.routers.confirmd_backend.tls=true'
      - 'traefik.http.routers.confirmd_backend.tls.certresolver=letsencrypt'
      - 'traefik.docker.network=traefik-network'

      - 'traefik.http.services.confirmd_backend.loadbalancer.passhostheader=true'
      - 'traefik.http.routers.confirmd_backend.middlewares=compresstraefik'
      - 'traefik.http.middlewares.compresstraefik.compress=true'

      # Services
      - 'traefik.http.services.confirmd_backend.loadbalancer.server.port=5511'
